### ISSUE TITLE
Define and Create query parameters for GET TRU-list

### ISSUE THREAD

**Issue by dubnemo** [aggateway/TraceabilityAPI#7]
deviceUUID
fieldUUID
farmerUUID
containerUUID

CTE-list is the same

**Comment by dubnemo** [comment]
Following were added
@crakerb-ship-it, @jtevis @ekwallace 

```
	- name: sinceLastDateTime
          in: query
          description: Returns resources that have been updated since the last time the endpoint has been called
          required: false
          schema:
            type: string
            format: date-time
        - name: greaterThanDateTime
          in: query
          description: Returns resources that have been updated since a specified UTC timestamp
          required: false
          schema:
            type: string
            format: date-time
        - name: lessThanDateTime
          in: query
          description: Returns resources that have been updated up to a specified UTC timestamp
          required: false
          schema:
            type: string
            format: date-time
        - name: farmerUUID
          in: query
          description: UUID for the farmer
          required: false
          schema:
            type: string
        - name: fieldUUID
          in: query
          description: UUID for the farmer's field
          required: false
          schema:
            type: string
        - name: deviceUID
          in: query
          description: UUID for the device used, planter, tender, auger
          required: false
          schema:
            type: string
        - name: containerUUID
          in: query
          description: UUID for the container of interest
          required: false
          schema:
            type: string
```
